# Generated by Django 4.0 on 2021-12-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='djangoClasses',
            new_name='djangoClasse',
        ),
    ]
