# Generated by Django 4.0 on 2021-12-31 20:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('courseNumber', models.IntegerField()),
                ('instructor', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.FloatField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
